wallpaper {
    monitor = eDP-1
    path = ~/.local/wallpapers/wallpaper3.png
    fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = ~/.local/wallpapers/wallpaper2.png
	fit_mode = cover
}

splash = false
