#General
shell zsh
cursor_shape block
sync_to_monitor no
scrollback_indicator_opacity 0.0
window_padding_width 20
confirm_os_window_close 0

#Font
font_family firaCode Nerd Font
font_style Regular
font_size 12.0
enable_ligatures yes

#Theme
background_opacity 0.98
background_blur 0

cursor #ff7c0b
cursor_text_color background

url_color #275d7d

foreground #fafaf9
background #292424

selection_foreground #292424
selection_background #f7db90

color0 #292424
color8 #47403e

color1 #db3727
color9 #f77e72

color2 #a4c459
color10 #bdd680

color3 #eae028
color11 #f1ee58

color4 #509fc6
color12 #9ac7df

color5 #d28ce0
color13 #e4baed

color6 #85dadb
color14 #b7eaea

color7 #fafaf9
color15 #a89f9e

mark1_foreground #292424
mark1_background #509fc6

mark2_foreground #292424
mark2_background #d28ce0

mark3_foreground #292424
mark3_background #eae028
